server:
  port: 8083

spring:
  application:
    name: library-service

  cassandra:
    contact-points: ${LIBRARY_CASSANDRA_CONTACT_POINTS:localhost}
    port: ${LIBRARY_CASSANDRA_PORT:9042}
    keyspace-name: ${LIBRARY_CASSANDRA_KEYSPACE:spotify_library}
    local-datacenter: ${LIBRARY_CASSANDRA_LOCAL_DATACENTER:datacenter1}
    schema-action: CREATE_IF_NOT_EXISTS

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}