server:
  port: 8082

spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  application:
    name: auth-service
  profiles:
    active: dev
#    active: docker

  datasource:
    url: jdbc:mysql://localhost:3307/spotify_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: spotify_user
    password: spotify_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  bootstrap:
    admin:
      email: ${ADMIN_EMAIL:}
      username: ${ADMIN_USERNAME:}
      password-b64: ${ADMIN_PASSWORD_B64:}
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: 900000
      refresh-token:
        expiration: 604800000