server:
  port: 8081

spring:
  application:
    name: catalog-service

  # Docker'da aya?a kald?rd???m?z PostgreSQL bilgileri
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify_catalog
    username: spotify_user
    password: spotify_password
    driver-class-name: org.postgresql.Driver

  # Hibernate (ORM) Ayarlar?
  jpa:
    hibernate:
      ddl-auto: update # Entity s?n?flar?m?za g�re tablolar? otomatik olu?turur/g�nceller
    show-sql: true # Konsolda �al??an SQL sorgular?n? g�rmek i�in
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false